version: 2.1
jobs:
  test-35:
    docker:
      - image: circleci/python:3.5
    environment:
      &std_env
      TERM: xterm
      LANG: en_US.UTF-8
    working_directory: ~/json-syntax
    steps:
      - checkout
      - run:
          name: Set up virtualenv
          command: |
            pip install poetry
            poetry install

      - run:
          name: Run tests
          command: |
            poetry run pytest tests/

      - store_artifacts:  # If a property test fails, this contains the example that failed.
          path: ".hypothesis"
          destination: ".hypothesis"
  test-36:
    docker:
      - image: circleci/python:3.6
    environment: *std_env
    steps:
      &std_steps
      - checkout
      - run:
          name: Set up virtualenv
          command: |
            pip install poetry
            poetry install

      - run:
          name: Run tests
          command: |
            poetry run pytest --doctest-modules json_syntax/ tests/

      - store_artifacts:  # If a property test fails, this contains the example that failed.
          path: ".hypothesis"
          destination: ".hypothesis"
    working_directory: ~/json-syntax
  test-37:
    docker:
      - image: circleci/python:3.7
    environment: *std_env
    steps: *std_steps
    working_directory: ~/json-syntax
  test-38:
    docker:
      - image: circleci/python:3.8
    environment: *std_env
    steps: *std_steps
    working_directory: ~/json-syntax

workflows:
  test:
    jobs:
      - test-35
      - test-36
      - test-37
      - test-38
