version: 2.1
jobs:
  test-34:
    docker:
      - image: circleci/python:3.4
    environment:
      &std_env
      TERM: xterm
      LANG: en_US.UTF-8
      PIP_DISABLE_PIP_VERSION_CHECK: 1
    working_directory: ~/json-syntax
    steps:
      &steps34
      - checkout
      - run:
          name: Set up virtualenv
          command: |
            pip install poetry>=1.0.0
            poetry install

      - run:
          name: Run tests
          command: |
            poetry run pytest tests/

      - store_artifacts:  # If a property test fails, this contains the example that failed.
          path: ".hypothesis"
          destination: ".hypothesis"
  test-35:
    docker:
      - image: circleci/python:3.5
    environment: *std_env
    steps: *steps34
    working_directory: ~/json-syntax
  test-36:
    docker:
      - image: circleci/python:3.6
    environment: *std_env
    working_directory: ~/json-syntax
    steps:
      &steps36
      - checkout
      - run:
          name: Set up virtualenv
          command: |
            pip install poetry>=1.0.0
            poetry install

      - run:
          name: Run tests
          command: |
            poetry run pytest --doctest-modules json_syntax/ tests/

      - store_artifacts:  # If a property test fails, this contains the example that failed.
          path: ".hypothesis"
          destination: ".hypothesis"
  test-37:
    docker:
      - image: circleci/python:3.7
    environment: *std_env
    steps: *steps36
    working_directory: ~/json-syntax
  test-38:
    docker:
      - image: circleci/python:3.8
    environment: *std_env
    steps: *steps36
    working_directory: ~/json-syntax

workflows:
  test:
    jobs:
      - test-34
      - test-35
      - test-36
      - test-37
      - test-38
